"""Domain contracts for CareerBoost AI."""

from careerboost_api.domain.analysis import (
    AnalysisError,
    AnalysisErrorCategory,
    AnalysisStagePlaceholder,
    AnalysisStatus,
    DetectedResumeSection,
    ExtractionConfidence,
    ExtractionStatus,
    FutureStageStatus,
    IntakeStatus,
    ResumeAnalysisContract,
    ResumeCompletenessContract,
    ResumeExtractionContract,
    ResumeIntakeContract,
)
from careerboost_api.domain.ats import (
    AtsFeedbackContract,
    AtsFeedbackIssue,
    AtsFeedbackStatus,
    AtsIssueCategory,
    AtsIssueSeverity,
    AtsKeywordCoveragePlaceholder,
    AtsScorePlaceholder,
    AtsScoreStatus,
)
from careerboost_api.domain.resume_sections import ResumeSectionName
from careerboost_api.domain.roles import (
    InternshipRoleName,
    RoleMatchCandidate,
    RoleMatchConfidenceState,
    RoleMatchContractStatus,
    RoleMatchesContract,
    RoleMatchStatus,
)
from careerboost_api.domain.skills import (
    SkillEvidenceLevel,
    SkillSignal,
    SkillSignalCategory,
    SkillSignalEvidence,
    SkillSignalsContract,
    SkillSignalStatus,
    SkillSourceArea,
)

__all__ = [
    "AnalysisError",
    "AnalysisErrorCategory",
    "AnalysisStagePlaceholder",
    "AnalysisStatus",
    "AtsFeedbackContract",
    "AtsFeedbackIssue",
    "AtsFeedbackStatus",
    "AtsIssueCategory",
    "AtsIssueSeverity",
    "AtsKeywordCoveragePlaceholder",
    "AtsScorePlaceholder",
    "AtsScoreStatus",
    "DetectedResumeSection",
    "ExtractionConfidence",
    "ExtractionStatus",
    "FutureStageStatus",
    "IntakeStatus",
    "InternshipRoleName",
    "ResumeAnalysisContract",
    "ResumeCompletenessContract",
    "ResumeExtractionContract",
    "ResumeIntakeContract",
    "ResumeSectionName",
    "RoleMatchCandidate",
    "RoleMatchConfidenceState",
    "RoleMatchContractStatus",
    "RoleMatchesContract",
    "RoleMatchStatus",
    "SkillEvidenceLevel",
    "SkillSignal",
    "SkillSignalCategory",
    "SkillSignalEvidence",
    "SkillSignalsContract",
    "SkillSignalStatus",
    "SkillSourceArea",
]
