"""Domain contracts for CareerBoost AI."""

from careerboost_api.domain.analysis import (
    AnalysisError,
    AnalysisErrorCategory,
    AnalysisStagePlaceholder,
    AnalysisStatus,
    DetectedResumeSection,
    ExtractionConfidence,
    ExtractionStatus,
    FutureStageStatus,
    IntakeStatus,
    ResumeAnalysisContract,
    ResumeCompletenessContract,
    ResumeExtractionContract,
    ResumeIntakeContract,
    ResumeSectionName,
)
from careerboost_api.domain.ats import (
    AtsFeedbackContract,
    AtsFeedbackIssue,
    AtsFeedbackStatus,
    AtsIssueCategory,
    AtsIssueSeverity,
    AtsKeywordCoveragePlaceholder,
    AtsScorePlaceholder,
    AtsScoreStatus,
)

__all__ = [
    "AnalysisError",
    "AnalysisErrorCategory",
    "AnalysisStagePlaceholder",
    "AnalysisStatus",
    "AtsFeedbackContract",
    "AtsFeedbackIssue",
    "AtsFeedbackStatus",
    "AtsIssueCategory",
    "AtsIssueSeverity",
    "AtsKeywordCoveragePlaceholder",
    "AtsScorePlaceholder",
    "AtsScoreStatus",
    "DetectedResumeSection",
    "ExtractionConfidence",
    "ExtractionStatus",
    "FutureStageStatus",
    "IntakeStatus",
    "ResumeAnalysisContract",
    "ResumeCompletenessContract",
    "ResumeExtractionContract",
    "ResumeIntakeContract",
    "ResumeSectionName",
]
